#!/usr/bin/python

import json, webbrowser, sys, time
from requests import *


flags = ['-m']


def get_flags():
	global flags
	f = [x for x in sys.argv if x in flags]
	assert(len(sys.argv) % 2 != 0)
	pass


def get_loc(ip):
    data = json.loads(get('http://ip-api.com/json/{0}'.format(ip)).text)
    return ((data['lat'], data['lon']))


def main():
	if len(sys.argv) < 2:
		print 'Provide an IP'
		return

	cords = get_loc(sys.argv[1])
	webbrowser.open_new('https://www.google.com/maps/search/?api=1&query={0},{1}'.format(cords[0], cords[1]))
	time.sleep(2)
	sys.exit(0)

main()


